package view;

import java.awt.Color;

public class DangNhap extends javax.swing.JFrame {

    public DangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        nutDangNhap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mesError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tài khoản");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 65, -1));

        jLabel2.setText("Mật khẩu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 56, -1));
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 136, -1));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 136, -1));

        nutDangNhap.setBackground(new java.awt.Color(255, 255, 51));
        nutDangNhap.setForeground(new java.awt.Color(51, 0, 51));
        nutDangNhap.setText("Đăng nhập");
        nutDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(nutDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, 34));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Đăng nhập");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));
        getContentPane().add(mesError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 178, 17));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nutDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutDangNhapActionPerformed
        // TODO add your handling code here:
        
        String username = account.getText();
        String password = passwordField.getText();
        
        if (username.equals("1") && password.equals("1")) {
            setVisible(false);

            // Tạo và hiển thị màn hình mới
            HotelMS nextView = new HotelMS();
            nextView.setVisible(true);
        } else {
            mesError.setText("TK or MK không đúng!");
            mesError.setForeground(Color.RED);
        }
    }//GEN-LAST:event_nutDangNhapActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mesError;
    private javax.swing.JButton nutDangNhap;
    private javax.swing.JTextField passwordField;
    // End of variables declaration//GEN-END:variables
}
