
package view;

import control.listCustomerControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import module.Customer;


public class DSCustomer extends javax.swing.JFrame {
    private listCustomerControl listcustomer;
    /**
     * Creates new form DSCustomer
     */
    public DSCustomer() {
        initComponents();
        listcustomer = new listCustomerControl();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        modify = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        modify.setText("sửa");
        modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifyMousePressed(evt);
            }
        });
        jPopupMenu1.add(modify);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "CustomerID", "Name", "Phone", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyMousePressed
        // TODO add your handling code here:
        modifyCustomer();
    }//GEN-LAST:event_modifyMousePressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        jPopupMenu1.show(jTable1, evt.getX(), evt.getY());
    }//GEN-LAST:event_jTable1MouseReleased

    private void displayCustomerData() {
        // Lấy model của JTable
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        // Xóa dữ liệu cũ
        tableModel.setRowCount(0);

        // Lấy dữ liệu từ loaddata
        List<Object[]> customerData = listcustomer.loadCustomerData();

        // Thêm dữ liệu vào bảng
        for (Object[] rowData : customerData) {
            tableModel.addRow(rowData);
        }
    }
    
    private void modifyCustomer() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            try {
                //int id = JOptionPane.showInputDialog(null, "Nhập id mới", jTable1.getValueAt(selectedRow, 0));
                int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
                String name = JOptionPane.showInputDialog(null, "Nhập tên mới", jTable1.getValueAt(selectedRow, 1));
                int phone = Integer.parseInt(jTable1.getValueAt(selectedRow, 2).toString());
                String address = JOptionPane.showInputDialog(null, "Nhập địa chỉ mới", jTable1.getValueAt(selectedRow, 3));

                // Kiểm tra tính hợp lệ của dữ liệu
                if (name == null || name.trim().isEmpty() || address == null || address.trim().isEmpty()) {
                    throw new IllegalArgumentException("Tên và địa chỉ không được để trống.");
                }

                // Tạo đối tượng Customer
                Customer customer = new Customer(id, name, phone, address);

                // Cập nhật dữ liệu vào bảng
                jTable1.setValueAt(customer.getName(), selectedRow, 1);
                jTable1.setValueAt(customer.getAddress(), selectedRow, 2);

                // Cập nhật dữ liệu vào database
                // updateCustomerInDatabase(customer);

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "ID không hợp lệ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem modify;
    // End of variables declaration//GEN-END:variables
}
