package view;

import control.loadData;
import control.confirmBookingControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import module.Payment;
import java.sql.SQLException;

public class ListBookRoom extends javax.swing.JFrame {

    private loadData loaddata;
    private confirmBookingControl confirm;

    /**
     * Creates new form BookRoom
     */
    public ListBookRoom() {
        initComponents();
        loaddata = new loadData();
        confirm = new confirmBookingControl();
        displayBookingData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cancelbutton = new javax.swing.JButton();
        confirmbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "bookingID", "customerID", "roomID", "checkInDate", "checkOutDate", "status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cancelbutton.setText("cancel booking");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        confirmbutton.setText("confirm booking");
        confirmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(confirmbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(cancelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbuttonActionPerformed
        // TODO add your handling code here:
        confirmBooking();
    }//GEN-LAST:event_confirmbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // TODO add your handling code here:
        cancelBooking();
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void displayBookingData() {
        // Lấy model của JTable
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        // Xóa dữ liệu cũ
        tableModel.setRowCount(0);

        // Lấy dữ liệu từ loaddata
        List<Object[]> bookingData = loaddata.loadBookingData();

        // Thêm dữ liệu vào bảng
        for (Object[] rowData : bookingData) {
            tableModel.addRow(rowData);
        }
    }

    public void confirmBooking() {

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            // kiểm tra status
            String pstatus = (String) jTable1.getValueAt(selectedRow, 5);
            if (pstatus.equals("waiting")) {
                // Lấy bookingID từ dòng được chọn
                int bookingID = (int) jTable1.getValueAt(selectedRow, 0);
                // lấy giá 
                int total = confirm.getRoomPriceFromBooking(bookingID);

                // Gọi controller để xử lý việc xác nhận và tạo Payment
                Payment payment = new Payment(bookingID, total);
                confirm.savePayment(payment);

                // Cập nhật trạng thái của booking thành "confirm"
                confirm.updateBookingStatus(bookingID);
                jTable1.setValueAt("confirm", selectedRow, 5);
                JOptionPane.showMessageDialog(null, "Xác nhận thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Đã xác nhận rồi!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chưa chọn booking nào!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void cancelBooking() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbutton;
    private javax.swing.JButton confirmbutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
