package view;

import control.loadData;
import control.modifyCustomerControl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import module.Customer;

public class ListCustomer extends javax.swing.JFrame {

    private loadData loaddata;
    private modifyCustomerControl modifycustomer;

    /**
     * Creates new form DSCustomer
     */
    public ListCustomer() {
        initComponents();
        loaddata = new loadData();
        modifycustomer = new modifyCustomerControl();
        displayCustomerData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        modify = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        modify.setText("sửa");
        modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modifyMousePressed(evt);
            }
        });
        jPopupMenu1.add(modify);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerID", "Name", "Phone", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyMousePressed
        // TODO add your handling code here:
        modifyCustomer();
    }//GEN-LAST:event_modifyMousePressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        jPopupMenu1.show(jTable1, evt.getX(), evt.getY());
    }//GEN-LAST:event_jTable1MouseReleased

    private void displayCustomerData() {
        // Lấy model của JTable
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        // Xóa dữ liệu cũ
        tableModel.setRowCount(0);

        // Lấy dữ liệu từ loaddata
        List<Object[]> customerData = loaddata.loadCustomerData();

        // Thêm dữ liệu vào bảng
        for (Object[] rowData : customerData) {
            tableModel.addRow(rowData);
        }
    }

    private void modifyCustomer() {
        int selectedRow = jTable1.getSelectedRow();

        try {
            String name = JOptionPane.showInputDialog(null, "Nhập tên mới", jTable1.getValueAt(selectedRow, 1));
            String numberphone = JOptionPane.showInputDialog(null, "Nhập phone mới", jTable1.getValueAt(selectedRow, 2));
            String address = JOptionPane.showInputDialog(null, "Nhập địa chỉ mới", jTable1.getValueAt(selectedRow, 3));

            // Kiểm tra tính hợp lệ của dữ liệu
            if (name == null || name.trim().isEmpty() || numberphone == null || numberphone.trim().isEmpty()) {
                throw new IllegalArgumentException("Tên và số điện thoại không được để trống.");
            }
            int phone = 0;
            try {
                phone = Integer.parseInt(numberphone);
                jTable1.setValueAt(name, selectedRow, 1);
                jTable1.setValueAt(phone, selectedRow, 2);
                jTable1.setValueAt(address, selectedRow, 3);
                JOptionPane.showMessageDialog(this, "sửa thành công.");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "phone nhập sai.");
            }

            // Cập nhật dữ liệu vào database
            int customerID = (int) jTable1.getValueAt(selectedRow, 0);
            Customer customer = new Customer(customerID, name, phone, address);
            modifycustomer.modifyCustomerToDatabase(customer);

        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem modify;
    // End of variables declaration//GEN-END:variables
}
